- test/ERC4626WrapperBase.t.sol
- test/mainnet/ERC4626MainnetMorphoSteakhouseUSDC.t.sol
- test/mainnet/ERC4626MainnetMorphoSteakhouseWUSDL.t.sol
Improve Base ERC4626 Fork Test comments
> Improve Base ERC4626 Fork Test comments

- .github/workflows/ci.yml
- foundry.toml
- test/ERC4626WrapperBase.t.sol
- test/sonic/ERC4626SiloV2.t.sol
> Add tests for Silo V2's ERC4626, also add sonic network

- test/sonic/ERC4626Avalon.t.sol
Avalon is an aave fork on Sonic
> adding avalon wrapper

- test/mainnet/ERC4626MainnetMorphoGauntletWethE.t.sol
- test/mainnet/ERC4626MainnetMorphoIndexCoopHyEth.t.sol
This PR is related to [code review PR #214](https://github.com/balancer/code-review/pull/214)
- [Gauntlet WETH Ecosystem (gtWETHe) ](https://etherscan.io/token/0x1e6ffa4e9F63d10B8820A3ab52566Af881Dab53c)
- Tests are passing :green_circle: 
- [IndexCoop hyETH (mhyETH)](https://etherscan.io/token/0x701907283a57FF77E255C3f1aAD790466B8CE4ef)
- Tests are passing :green_circle:
> Add tests for Morpho gtWETHe & mhyETH

- Readme.md
- test/ERC4626WrapperBase.t.sol
- test/mainnet/ERC4626MainnetSfrxEth.t.sol
This PR aims to help other developers to make their ERC4626 tests to pass.
> Debug documentation

- foundry.toml
Add Base and Arbitrum RPCs to env variables and forge
> Add Base and Arbitrum RPCs

- test/sonic/ERC4626AvalonSolvBTC.t.sol
- test/sonic/ERC4626AvalonSolvBTCbbn.t.sol
Required to add a test for each token. All are passing
> adding test for each token

- test/mainnet/ERC4626MainnetAavePyusd.t.sol
> ERC4626MainnetAavePyusdTest

- test/base/ERC4626BaseAaveCbBTC.t.sol
- test/base/ERC4626BaseAaveCbETH.t.sol
- test/base/ERC4626BaseAaveEzETH.t.sol
- test/base/ERC4626BaseAaveUSDC.t.sol
- test/base/ERC4626BaseAaveUSDbC.t.sol
- test/base/ERC4626BaseAaveWeETH.t.sol
- test/base/ERC4626BaseAaveWeth.t.sol
- test/base/ERC4626BaseAaveWstETH.t.sol
> First set of Aave wrappers on Base

- test/sonic/ERC4626SonicSiloSolvBtcBbn.t.sol
> add solvbtc.bbn silo

- test/sonic/ERC4626EulerMEVscETH.sol
- test/sonic/ERC4626EulerMEVwETH.sol
> euler sceth and weth

- test/arbitrum/ERC4626ArbitrumFluidWeth.t.sol
- test/base/ERC4626BaseFluidWeth.t.sol
fluid weth for both arbitrum and base. Utilising the minDeposit from the mainnet tests
> test: add fweth base and arbitrum

- test/sonic/ERC4626SonicSiloUsdc23.sol
- test/sonic/ERC4626SonicSiloWS28.sol
> two new silo markets

- test/sonic/ERC4626SonicSiloFrxUSD37.sol
> silo frxusd

- test/sonic/ERC4626SonicSiloScETH47.sol
- test/sonic/ERC4626SonicSiloScUSD46.sol
- test/sonic/ERC4626SonicSiloUSDC33.sol
- test/sonic/ERC4626SonicSiloWETH35.sol
Add new Silo markets
scETH: https://v2.silo.finance/markets/sonic/ptwstksceth29may-sceth-47
scUSD: https://v2.silo.finance/markets/sonic/ptausdc14aug-scusd-46
wETH: https://v2.silo.finance/markets/sonic/ptwstksceth29may-eth-35
USDC: https://app.silo.finance/markets/sonic/eggs-usdc-33
> add new silo markets

- .github/workflows/ci.yml
- foundry.toml
- test/ERC4626WrapperBase.t.sol
- test/optimism/ERC4626OptimismAaveAave.t.sol
- test/optimism/ERC4626OptimismAaveDai.t.sol
- test/optimism/ERC4626OptimismAaveLUSD.t.sol
- test/optimism/ERC4626OptimismAaveLink.t.sol
- test/optimism/ERC4626OptimismAaveOP.t.sol
- test/optimism/ERC4626OptimismAaveReth.t.sol
- test/optimism/ERC4626OptimismAaveSUSD.t.sol
- test/optimism/ERC4626OptimismAaveUSDC.t.sol
- test/optimism/ERC4626OptimismAaveUSDCe.t.sol
- test/optimism/ERC4626OptimismAaveUSDT.t.sol
- test/optimism/ERC4626OptimismAaveWbtc.t.sol
- test/optimism/ERC4626OptimismAaveWeth.t.sol
- test/optimism/ERC4626OptimismAaveWstETH.t.sol
> add aave on op

- test/sonic/ERC4626EulerMEVwS.sol
Add the Euler wS market in the MEV capital cluster: https://app.euler.finance/vault/0x9144C0F0614dD0acE859C61CC37e5386d2Ada43A?network=sonic
> add Euler wS market

- test/sonic/ERC4626SonicSiloUSDC36.sol
Silo USDC market 36: https://v2.silo.finance/markets/sonic/sts-usdc-36
> add usdc 36

- test/sonic/ERC4626SonicStabilityUSDC.sol
- test/sonic/ERC4626SonicStabilityscUSD.sol
> add stability usd

- .github/workflows/ci.yml
- foundry.toml
Configures Forge tests to run across multiple networks in parallel using a matrix strategy, improving test coverage.
Increases the number of fuzzing runs for more thorough testing.
> Improves Forge testing and fuzzing

- .github/workflows/ci.yml
- foundry.toml
- test/ERC4626WrapperBase.t.sol
- test/hyperevm/ERC4626FelixUSDe.t.sol
- test/hyperevm/ERC4626HyperdriveUSDe.t.sol
- test/hyperevm/ERC4626HyperlendUSDT0.t.sol
Tests on HyperEVM of the following tokens:
* Hyperlend USDT0: 0xb99E85bCF89d483506125701Bb98957542e47a0F
* Felix USDe: 0x835FEBF893c6DdDee5CF762B0f8e31C5B06938ab
* Hyperdrive USDe: 0x167101B7994c1c206B5A20A401b1F771EDbE988f
> HyperEVM tokens

- test/hyperevm/ERC4626FelixUSDhl.t.sol
- test/hyperevm/ERC4626GauntletUSDT0Vault.t.sol
- test/hyperevm/ERC4626hyUSD₮0(Looped HYPE).t.sol
- test/mainnet/ERC4626SteakhouseInifiniFiUSDC.t.sol
The token is hyUSD₮0 (Looped HYPE)
> test: add Hypurrfi's hyUSDT0

- test/hyperevm/ERC4626FelixUSDT0.t.sol
0xFc5126377F0efc0041C0969Ef9BA903Ce67d151e - hyperevm
> test: add Felix's USDT0

- test/hyperevm/ERC4626HyperbeatUSDe.t.sol
hyperevm - 0x5eEC795d919FA97688Fb9844eeB0072E6B846F9d hyperbeat
> test: add hyperbeat usde

- test/hyperevm/ERC4626HyperbeatMCHype.t.sol
Hyperevm - 0xd19e3d00f8547f7d108abFD4bbb015486437B487 - Hyperbeat's WHYPE
> test: add hyperbeat whype

- test/hyperevm/ERC4626FelixUSDhl2.t.sol
feUSDhl2 - 0x66c71204B70aE27BE6dC3eb41F9aF5868E68fDb6 on hyperevm
> test: add usdhl2

- test/mainnet/ERC4626MainnetStcUSD.t.sol
- cUSD https://etherscan.io/address/0xcCcc62962d17b8914c62D74FfB843d73B2a3cccC
- stcUSD https://etherscan.io/address/0x88887bE419578051FF9F4eb6C858A951921D8888
> cap stc usd

- test/sonic/ERC4626SonicSiloVaultSCUSDMithras.sol
New silo vault for scUSD: https://v2.silo.finance/vaults/sonic/0x391b3F70E254d582588B27e97E48D1CFcdf0BE7e?action=deposit
> mithras silo vault
